### ISSUE TITLE
Open source scrubscribers.com?

### ISSUE THREAD

**Issue by Lumez** [HatScrubs/GameAccess#18]
Was just wondering if it would it be possible to open source the scrubscribers.com code? I know myself and others would love to help out with the project if we could :)

**Comment by stygiansabyss** [comment]
Hi!  Truly happy so many people want to help out :)  Quite a few have offered.  At this time we have a pretty good group that is working on the code and will be continuing to do so.

As far as open source itself, we don't want to do that since this gives the gents something that is unique to them. The goal is to get them and their community more benefit, we aim to keep this code closed at this time.

Thank you again for the offer though :)

**Comment by Lumez** [comment]
Ah sure, no worries!

Yeah, I fully understand you want to give the guys something unique, it certainly makes the community experience special :) And yes, thinking on it more, keeping it closed for now would probably help achieve that best.

Thanks for the work you've done so far! :D And just let me know if your looking for an extra pair of hands at some point in the future!

**Comment by stygiansabyss** [comment]
I will gladly keep you in mind if we expand in the future.  Looking at your GH profile see you have used laravel in the past (at least to version 4).  Are you up to date on version 5.1+ and all of it's new features?

**Comment by Lumez** [comment]
Awesome, cheers! Yes, I have used Laravel 4 on projects in the past, and yeah, I've kept up to date with the changes to it (yay for event broadcasting as this is one of the reasons I moved away from Laravel) but haven't used it in a real project since. Mainly been using Node.js for the other things I've built recently.

**Comment by stygiansabyss** [comment]
Cool.  I'll definitely keep it in mind then :)
